name: TryLibs
version: '1.0.0'
main: com.trynocs.tryLibs.TryLibs
api-version: '1.20'
authors: [ "Trynocs" ]
softdepend: [ Vault ]
description: Utility library for Bukkit/Spigot/Paper plugins
load: STARTUP
loadbefore: [BPUtils, BPJobs]
api: true
